### ISSUE TITLE
No launch button?

### ISSUE THREAD

**Issue by fredzett** [QuantEcon/quantecon-book-theme#175]
First of all: thanks for the great theme. I really like it!

One thing I cannot figure out: the launch buttons do not show anymore once I switch the theme to "quantecon_book_theme". 

This is what I use:

```
sphinx:
  config:
    html_theme: quantecon_book_theme
    html_theme_options:
      repository_url: https://github.com/fredzett/CodingBook
      repository_branch: main
      launch_buttons:
        colab_url: https://colab.research.google.com
      persistent_sidebar: true
```

Is this a bug in the theme or am I doing something wrong?
