### ISSUE TITLE
Disparity of config variable reading between sphinx-book-theme and quantecon-book-theme

### ISSUE THREAD

**Issue by AakashGfude** [QuantEcon/quantecon-book-theme#31]
`sphinx-book-theme` seems to be able to read theme variables like this:

```
html:
   google_analytics_id: your-id
``` 

whereas `quantecon-book-theme` needs the following structure:

```
sphinx:
   config:
      html_theme_options:
         google_analytics_id: put-id-here
```
